"""Export a trained (or scaffolded) token-classification model to ONNX int8.

Produces a transformers.js-compatible folder (`web/models/<name>/`) that the browser
demo loads with `pipeline("token-classification", ..., { device: "webgpu", dtype: "q8" })`.

Two modes:
- ``--model-dir <ckpt>``: export a real fine-tuned checkpoint produced by ``pii-train``.
- ``--scaffold``: build an UNTRAINED head on ``config.MODEL_RUBERT`` with the BIO label
  set from ``labels.py``. Predictions are random, but the architecture, tokenizer and
  labels match a real checkpoint, so swapping one in later needs no frontend changes.

Also writes ``web/labels.generated.js`` (entity -> tag) from ``ENTITY_LABELS``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import torch
from onnxruntime.quantization import QuantType, quantize_dynamic
from transformers import AutoModelForTokenClassification, AutoTokenizer

from . import config
from .labels import ENTITY_LABELS, NUM_LABELS, id2label, label2id

# Repo root (src/pii_ner/export_onnx.py -> parents[2] == repo root).
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "web" / "models" / "pii-ner-rubert"
LABELS_JS = REPO_ROOT / "web" / "labels.generated.js"


def slugify_tag(label: str) -> str:
    """Turn a Russian entity label into a SHORT_UPPERCASE tag for obfuscation."""
    slug = re.sub(r"[^\w]+", "_", label, flags=re.UNICODE).strip("_")
    return slug.upper()


def write_labels_js(path: Path = LABELS_JS) -> dict[str, str]:
    """Emit web/labels.generated.js mapping each entity label -> placeholder tag."""
    tags = {label: f"[{slugify_tag(label)}]" for label in ENTITY_LABELS}
    body = ",\n".join(f"  {json.dumps(k, ensure_ascii=False)}: "
                      f"{json.dumps(v, ensure_ascii=False)}" for k, v in tags.items())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// Generated by pii-export-onnx from pii_ner.labels.ENTITY_LABELS -- do not edit.\n"
        f"export const LABEL_TAGS = {{\n{body},\n}};\n",
        encoding="utf-8",
    )
    return tags


def _load_model_and_tokenizer(model_dir: str | None, scaffold: bool):
    if scaffold:
        print(f"Scaffolding UNTRAINED head on {config.MODEL_RUBERT} "
              f"({NUM_LABELS} BIO labels) ...")
        tok = AutoTokenizer.from_pretrained(config.MODEL_RUBERT)
        model = AutoModelForTokenClassification.from_pretrained(
            config.MODEL_RUBERT,
            num_labels=NUM_LABELS,
            id2label=id2label,
            label2id=label2id,
        )
        return model, tok
    print(f"Loading trained checkpoint from {model_dir} ...")
    tok = AutoTokenizer.from_pretrained(model_dir)
    model = AutoModelForTokenClassification.from_pretrained(model_dir)
    return model, tok


def _export_fp32(model, tokenizer, fp32_path: Path) -> None:
    """Trace the token-classifier to ONNX with torch.onnx (no optimum dependency)."""
    model.eval()
    model.config.return_dict = False  # so forward returns a plain (logits,) tuple
    enc = tokenizer("Пример текста для трассировки.", return_tensors="pt")
    input_ids, attention_mask = enc["input_ids"], enc["attention_mask"]
    dynamic = {0: "batch", 1: "sequence"}
    with torch.no_grad():
        torch.onnx.export(
            model,
            (input_ids, attention_mask),
            str(fp32_path),
            input_names=["input_ids", "attention_mask"],
            output_names=["logits"],
            dynamic_axes={
                "input_ids": dynamic,
                "attention_mask": dynamic,
                "logits": dynamic,
            },
            opset_version=17,
            do_constant_folding=True,
            dynamo=False,  # classic tracer (input_names/dynamic_axes); avoids onnxscript
        )


def export(model_dir: str | None, scaffold: bool, out: Path = DEFAULT_OUT) -> Path:
    model, tokenizer = _load_model_and_tokenizer(model_dir, scaffold)

    out.mkdir(parents=True, exist_ok=True)
    onnx_dir = out / "onnx"
    onnx_dir.mkdir(parents=True, exist_ok=True)

    # transformers.js layout: config.json + tokenizer files at the model root, and the
    # weights under onnx/. We save only config + tokenizer (not the torch weights).
    model.config.save_pretrained(out)
    tokenizer.save_pretrained(out)

    fp32 = onnx_dir / "model.onnx"
    print("Exporting to ONNX (torch.onnx, token-classification) ...")
    _export_fp32(model, tokenizer, fp32)

    quantized = onnx_dir / "model_quantized.onnx"
    print(f"Quantizing {fp32.name} -> onnx/{quantized.name} (int8) ...")
    quantize_dynamic(str(fp32), str(quantized), weight_type=QuantType.QInt8)

    tags = write_labels_js()

    print(f"\nExported to {out}")
    for p in sorted(out.rglob("*")):
        if p.is_file():
            print(f"  {p.relative_to(out)}  ({p.stat().st_size / 1e6:.1f} MB)")
    print(f"Wrote {LABELS_JS.relative_to(REPO_ROOT)} ({len(tags)} entity tags)")
    if scaffold:
        print("\nReminder: scaffold head is UNTRAINED -- predictions are random until you "
              "export a real checkpoint with --model-dir. Frontend wiring is functional.")
    return out
