# -*- coding: utf-8 -*-
"""expand_spans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1LufVJ4LFZdLt-TPaQfvTV046EWaJ_n

# Expand Spans to Word Boundaries

Расширяет предсказанные спаны сущностей до границ слов
"""

import pandas as pd
import ast
from typing import List, Tuple

# Загружаем данные
preds_df = pd.read_csv('llm-march2026-alfabank/bert_sample_pred.csv')
texts_df = pd.read_csv('llm-march2026-alfabank/private_test_dataset.csv')

print(f"Predictions: {len(preds_df)}")
print(f"Texts: {len(texts_df)}")
preds_df.head()

# Символы-разделители (на них останавливаемся при расширении)
STOP_CHARS = set(' \t\n.,;:!?()[]{}"\'-—–«»')

def expand_span_to_word_boundary(text: str, start: int, end: int) -> Tuple[int, int]:
    """
    Расширяет спан до границ слов (не включая пунктуацию и кавычки).
    """
    # Расширяем влево до разделителя
    new_start = start
    while new_start > 0 and text[new_start - 1] not in STOP_CHARS:
        new_start -= 1

    # Расширяем вправо до разделителя
    new_end = end
    while new_end < len(text) and text[new_end] not in STOP_CHARS:
        new_end += 1

    return new_start, new_end

# Тест функции
test_text = "Моя дата рождения 19 июня 1990 года."
print(f"Text: '{test_text}'")
print()

# Симулируем обрезанный спан
start, end = 18, 20  # только "19"
print(f"Original span: ({start}, {end}) = '{test_text[start:end]}'")

new_start, new_end = expand_span_to_word_boundary(test_text, start, end)
print(f"Expanded span: ({new_start}, {new_end}) = '{test_text[new_start:new_end]}'")

def expand_all_predictions(preds_df: pd.DataFrame, texts_df: pd.DataFrame) -> Tuple[pd.DataFrame, List[dict], List[dict]]:
    """
    Расширяет все предсказанные спаны до границ слов.
    Удаляет спаны, состоящие только из запятой.
    Возвращает DataFrame с расширенными предсказаниями, список изменений и список удалённых.
    """
    expanded_predictions = []
    changes = []
    removed = []

    for idx, row in preds_df.iterrows():
        pred_id = row['id']
        pred_str = row['Prediction']

        # Парсим предсказания
        try:
            entities = ast.literal_eval(pred_str)
        except:
            entities = []

        if not entities:
            expanded_predictions.append({'id': pred_id, 'Prediction': '[]'})
            continue

        # Получаем текст
        text = texts_df.loc[texts_df['id'] == pred_id, 'text'].values[0]

        new_entities = []
        for entity in entities:
            start, end, label = entity[0], entity[1], entity[2]
            span_text = text[start:end]

            # Удаляем спаны состоящие только из запятой или пунктуации
            if span_text.strip() in [',', '.', ';', ':', '!', '?', '']:
                removed.append({
                    'id': pred_id,
                    'label': label,
                    'span': (start, end),
                    'text': span_text,
                })
                continue  # Пропускаем этот спан

            new_start, new_end = expand_span_to_word_boundary(text, start, end)

            # Записываем изменение если спан изменился
            if new_start != start or new_end != end:
                changes.append({
                    'id': pred_id,
                    'label': label,
                    'old_span': (start, end),
                    'new_span': (new_start, new_end),
                    'old_text': span_text,
                    'new_text': text[new_start:new_end],
                })

            new_entities.append((new_start, new_end, label))

        expanded_predictions.append({'id': pred_id, 'Prediction': str(new_entities)})

    result_df = pd.DataFrame(expanded_predictions)
    return result_df, changes, removed

# Расширяем все предсказания
expanded_df, changes, removed = expand_all_predictions(preds_df, texts_df)

print(f"Total changes: {len(changes)}")
print(f"Total removed: {len(removed)}")

# Статистика по типам изменений
from collections import Counter

label_counts = Counter(ch['label'] for ch in changes)
print("Changes by label:")
for label, count in label_counts.most_common():
    print(f"  {label}: {count}")

# Смотрим удалённые спаны (только пунктуация)
print(f"REMOVED SPANS ({len(removed)}):")
print("=" * 50)

for rm in removed:
    print(f"ID {rm['id']} | {rm['label']} | span={rm['span']} | text='{rm['text']}'")

# Фильтруем только значимые изменения (исключаем кавычки «»)
significant_changes = [
    ch for ch in changes
    if not (ch['new_text'].startswith('«') and ch['new_text'].endswith('»'))
]

print(f"Significant changes (without quotes): {len(significant_changes)}")
print()

for ch in significant_changes:
    print(f"ID {ch['id']} | {ch['label']}")
    print(f"  '{ch['old_text']}' -> '{ch['new_text']}'")
    print()

# Сохраняем результат
output_file = "bert_expanded_pred.csv"
expanded_df.to_csv(output_file, index=False)
print(f"Saved to: {output_file}")

expanded_df.head(10)

# Сравниваем оригинал и расширенные
print("Original vs Expanded (first 5 non-empty):")
print()

count = 0
for idx, row in preds_df.iterrows():
    orig = row['Prediction']
    exp = expanded_df.loc[expanded_df['id'] == row['id'], 'Prediction'].values[0]

    if orig != '[]' and orig != exp:
        print(f"ID {row['id']}:")
        print(f"  ORIG: {orig}")
        print(f"  EXP:  {exp}")
        print()
        count += 1
        if count >= 5:
            break

"""# Post-Processing Hypotheses

Исследуем различные гипотезы для улучшения качества NER предсказаний
"""

# Подготовка данных для анализа
import re
from collections import defaultdict

def parse_all_predictions(preds_df, texts_df):
    """Парсит все предсказания и возвращает список с метаданными."""
    all_entities = []

    for idx, row in preds_df.iterrows():
        pred_id = row['id']
        pred_str = row['Prediction']

        try:
            entities = ast.literal_eval(pred_str)
        except:
            entities = []

        if not entities:
            continue

        text = texts_df.loc[texts_df['id'] == pred_id, 'text'].values[0]

        for entity in entities:
            start, end, label = entity[0], entity[1], entity[2]
            span_text = text[start:end]

            all_entities.append({
                'id': pred_id,
                'start': start,
                'end': end,
                'length': end - start,
                'label': label,
                'text': span_text,
                'full_text': text,
            })

    return all_entities

entities = parse_all_predictions(expanded_df, texts_df)
print(f"Total entities: {len(entities)}")

"""## Hypothesis 1: Short Spans (< 3 characters)

Слишком короткие спаны могут быть ошибками модели
"""

# Анализ коротких спанов с подробным контекстом
MIN_LENGTH = 3

short_spans = [e for e in entities if e['length'] < MIN_LENGTH]
print(f"Short spans (< {MIN_LENGTH} chars): {len(short_spans)} / {len(entities)} ({100*len(short_spans)/len(entities):.1f}%)")
print()

# Группируем по лейблам
short_by_label = defaultdict(list)
for e in short_spans:
    short_by_label[e['label']].append(e)

print("=" * 70)
print("SUSPICIOUS SHORT SPANS BY LABEL (with context)")
print("=" * 70)

for label, items in sorted(short_by_label.items(), key=lambda x: -len(x[1])):
    print(f"\n### {label}: {len(items)} spans ###")
    print("-" * 70)

    for item in items:
        ctx_start = max(0, item['start'] - 20)
        ctx_end = min(len(item['full_text']), item['end'] + 30)
        context = item['full_text'][ctx_start:ctx_end]

        # Помечаем спан в контексте
        rel_start = item['start'] - ctx_start
        rel_end = item['end'] - ctx_start
        highlighted = context[:rel_start] + f">>>{item['text']}<<<" + context[rel_end:]

        print(f"  ID {item['id']} | len={item['length']} | text='{item['text']}'")
        print(f"    Context: ...{highlighted}...")
        print()

# Hypothesis 1: Удаление коротких буквенных спанов
# Удаляем спаны типа "с" для дат регистрации - это ошибки модели

LABELS_TO_FILTER_SHORT_LETTERS = {
    'Дата регистрации по месту жительства или пребывания',
    'Дата окончания срока действия карты',
}

def is_only_letters(text):
    """Проверяет, состоит ли текст только из букв."""
    return text.strip().isalpha()

def should_remove_short_span(text, label, max_len=3):
    """
    Проверяет, нужно ли удалить короткий спан.
    Удаляем если:
    - длина <= max_len
    - класс в списке фильтрации
    - текст состоит только из букв (например "с")
    """
    if len(text) > max_len:
        return False
    if label not in LABELS_TO_FILTER_SHORT_LETTERS:
        return False
    if is_only_letters(text):
        return True
    return False

def remove_short_letter_spans(preds_df, texts_df):
    """Удаляет короткие буквенные спаны и возвращает новый DataFrame."""
    results = []
    removed_list = []

    for idx, row in preds_df.iterrows():
        pred_id = row['id']
        pred_str = row['Prediction']

        try:
            entities = ast.literal_eval(pred_str)
        except:
            entities = []

        if not entities:
            results.append({'id': pred_id, 'Prediction': '[]'})
            continue

        text = texts_df.loc[texts_df['id'] == pred_id, 'text'].values[0]

        new_entities = []
        for entity in entities:
            start, end, label = entity[0], entity[1], entity[2]
            span_text = text[start:end]

            if should_remove_short_span(span_text, label):
                ctx_start = max(0, start - 15)
                ctx_end = min(len(text), end + 25)
                removed_list.append({
                    'id': pred_id,
                    'label': label,
                    'text': span_text,
                    'context': text[ctx_start:ctx_end],
                })
            else:
                new_entities.append((start, end, label))

        results.append({'id': pred_id, 'Prediction': str(new_entities)})

    return pd.DataFrame(results), removed_list

# Применяем удаление
h1_df, h1_removed = remove_short_letter_spans(expanded_df, texts_df)

print(f"HYPOTHESIS 1: Removed {len(h1_removed)} short letter spans")
print("=" * 60)

for item in h1_removed:
    print(f"ID {item['id']} | {item['label']}")
    print(f"  Text: '{item['text']}'")
    print(f"  Context: ...{item['context']}...")
    print()

# Сохраняем
h1_output = "bert_h1_no_short_letters.csv"
h1_df.to_csv(h1_output, index=False)
print(f"Saved to: {h1_output}")

# ОТКЛЮЧЕНО: H3 Date Expansion
#
# ПРИЧИНА: Согласно ground truth разметке в train_dataset, короткие спаны для дат
# ("19", "1", "25", "05", "11" и т.д.) - это ПРАВИЛЬНАЯ разметка!
#
# Примеры из train:
#   Row 2881 | '1' | ...Я родился >>>1<<< января...
#   Row 2918 | '8' | ...во вторник, >>>8<<< августа 1989 года...
#   Row 2832 | '17' | ...Я родился >>>17<<< марта...
#   Row 2815 | '11' | ...1990 года в >>>11<<< часов 25 минут...
#
# Расширять НЕ НУЖНО - модель предсказывает правильно!

print("H3 (Date Expansion) - ОТКЛЮЧЕНО")
print("Короткие спаны для дат соответствуют ground truth разметке")
print()
print("Используем h1_df напрямую для следующих шагов")

# Просто копируем h1_df без изменений
h3_df = h1_df.copy()
h3_expansions = []  # Пустой список для совместимости

"""## Hypothesis 2: Overlapping Spans

Пересекающиеся спаны - оставляем больший, удаляем меньший
"""

def find_and_remove_overlapping(preds_df, texts_df):
    """
    Находит пересекающиеся спаны и оставляет только больший.
    Возвращает новый DataFrame и список удалённых спанов.
    """
    results = []
    removed_list = []

    for idx, row in preds_df.iterrows():
        pred_id = row['id']
        pred_str = row['Prediction']

        try:
            entities = ast.literal_eval(pred_str)
        except:
            entities = []

        if not entities:
            results.append({'id': pred_id, 'Prediction': '[]'})
            continue

        text = texts_df.loc[texts_df['id'] == pred_id, 'text'].values[0]

        # Сортируем по началу, потом по длине (больший первый)
        sorted_ents = sorted(entities, key=lambda x: (x[0], -(x[1] - x[0])))

        filtered = []
        for ent in sorted_ents:
            start, end, label = ent[0], ent[1], ent[2]
            span_text = text[start:end]

            # Проверяем пересечение с уже добавленными
            overlaps_with = None
            for existing in filtered:
                ex_start, ex_end, ex_label = existing[0], existing[1], existing[2]
                # Пересекаются если один начинается до конца другого
                if start < ex_end and end > ex_start:
                    overlaps_with = existing
                    break

            if overlaps_with:
                ex_start, ex_end, ex_label = overlaps_with
                ex_len = ex_end - ex_start
                cur_len = end - start

                if cur_len > ex_len:
                    # Текущий больше - удаляем старый, добавляем текущий
                    filtered.remove(overlaps_with)
                    filtered.append(ent)
                    removed_list.append({
                        'id': pred_id,
                        'removed': (ex_start, ex_end, ex_label),
                        'removed_text': text[ex_start:ex_end],
                        'kept': (start, end, label),
                        'kept_text': span_text,
                    })
                else:
                    # Старый больше или равен - удаляем текущий
                    removed_list.append({
                        'id': pred_id,
                        'removed': (start, end, label),
                        'removed_text': span_text,
                        'kept': overlaps_with,
                        'kept_text': text[ex_start:ex_end],
                    })
            else:
                filtered.append(ent)

        results.append({'id': pred_id, 'Prediction': str(filtered)})

    return pd.DataFrame(results), removed_list

# Применяем к результату после H3 (date expansion)
h2_df, h2_removed = find_and_remove_overlapping(h3_df, texts_df)

print(f"HYPOTHESIS 2: Removed {len(h2_removed)} overlapping spans (kept longer)")
print("=" * 60)

for item in h2_removed:
    print(f"ID {item['id']}:")
    print(f"  REMOVED: {item['removed']} = '{item['removed_text']}'")
    print(f"  KEPT:    {item['kept']} = '{item['kept_text']}'")
    print()

# Сохраняем
h2_output = "bert_h2_no_overlaps.csv"
h2_df.to_csv(h2_output, index=False)
print(f"Saved to: {h2_output}")

"""## Hypothesis 3: Long Spans (> 80 characters)

Слишком длинные спаны могут захватывать лишний контекст
"""

# Анализ длинных спанов (используем h2_df - результат после H1 и H2)
entities_h2 = parse_all_predictions(h2_df, texts_df)
MAX_LENGTH = 80

long_spans = [e for e in entities_h2 if e['length'] > MAX_LENGTH]
print(f"Long spans (> {MAX_LENGTH} chars): {len(long_spans)} / {len(entities_h2)} ({100*len(long_spans)/len(entities_h2):.1f}%)")
print()

# Группируем по лейблам
long_by_label = defaultdict(list)
for e in long_spans:
    long_by_label[e['label']].append(e)

print("By label:")
for label, items in sorted(long_by_label.items(), key=lambda x: -len(x[1])):
    print(f"\n{label}: {len(items)}")
    for item in items[:5]:
        print(f"  ID {item['id']} (len={item['length']}): '{item['text'][:60]}...' ")

"""## Hypothesis 4: Format Validation

Проверяем соответствие формата сущности её типу:
- Email должен содержать @
- Номер телефона должен содержать цифры
- ФИО должно содержать буквы
- CVV должен быть 3-4 цифры
- и т.д.
"""

# Правила валидации форматов
def validate_entity(text: str, label: str) -> Tuple[bool, str]:
    """
    Проверяет соответствие текста сущности её типу.
    Returns: (is_valid, reason)
    """
    text = text.strip()

    if label == "Email":
        if "@" not in text:
            return False, "Email без @"
        if not re.search(r'@[\w.-]+\.\w+', text):
            return False, "Некорректный формат email"

    elif label == "Номер телефона":
        digits = re.sub(r'\D', '', text)
        if len(digits) < 7:
            return False, f"Слишком мало цифр: {len(digits)}"

    elif label == "CVV/CVC":
        digits = re.sub(r'\D', '', text)
        if not (3 <= len(digits) <= 4):
            return False, f"CVV должен быть 3-4 цифры, got {len(digits)}"

    elif label == "ПИН код":
        digits = re.sub(r'\D', '', text)
        if len(digits) != 4:
            return False, f"ПИН должен быть 4 цифры, got {len(digits)}"

    elif label == "ФИО":
        if not re.search(r'[а-яА-ЯёЁa-zA-Z]', text):
            return False, "ФИО без букв"
        if re.match(r'^[\d\s\-]+$', text):
            return False, "ФИО только цифры"

    elif label == "СНИЛС клиента":
        digits = re.sub(r'\D', '', text)
        if len(digits) != 11:
            return False, f"СНИЛС должен быть 11 цифр, got {len(digits)}"

    elif label == "Сведения об ИНН":
        digits = re.sub(r'\D', '', text)
        if len(digits) not in [10, 12]:
            return False, f"ИНН должен быть 10 или 12 цифр, got {len(digits)}"

    elif label == "Номер карты":
        digits = re.sub(r'\D', '', text)
        if not (13 <= len(digits) <= 19):
            return False, f"Карта должна быть 13-19 цифр, got {len(digits)}"

    elif label == "Номер банковского счета":
        digits = re.sub(r'\D', '', text)
        if len(digits) != 20:
            return False, f"Счёт должен быть 20 цифр, got {len(digits)}"

    elif label == "Одноразовые коды":
        digits = re.sub(r'\D', '', text)
        if not (4 <= len(digits) <= 8):
            return False, f"OTP обычно 4-8 цифр, got {len(digits)}"

    elif label == "Дата рождения" or label == "Дата окончания срока действия карты":
        if not re.search(r'\d', text):
            return False, "Дата без цифр"

    return True, "OK"

# Проверяем все сущности (используем entities_h2)
invalid_entities = []
for e in entities_h2:
    is_valid, reason = validate_entity(e['text'], e['label'])
    if not is_valid:
        invalid_entities.append({**e, 'reason': reason})

print(f"Invalid entities: {len(invalid_entities)} / {len(entities_h2)} ({100*len(invalid_entities)/len(entities_h2):.1f}%)")
print()

# Группируем по причинам
by_reason = defaultdict(list)
for e in invalid_entities:
    by_reason[e['reason']].append(e)

print("By reason:")
for reason, items in sorted(by_reason.items(), key=lambda x: -len(x[1])):
    print(f"\n{reason}: {len(items)}")
    for item in items[:5]:
        print(f"  ID {item['id']} | {item['label']}: '{item['text'][:50]}'")
    if len(items) > 5:
        print(f"  ... and {len(items) - 5} more")

"""## Hypothesis 5: Suspicious Patterns

Детекция неестественных паттернов:
- Сущности, содержащие только стоп-слова
- Сущности, начинающиеся/заканчивающиеся пунктуацией
- Сущности с подозрительным контекстом
"""

# Детекция подозрительных паттернов
STOP_WORDS = {'и', 'в', 'на', 'с', 'по', 'к', 'от', 'до', 'за', 'из', 'у', 'о', 'для', 'при', 'а', 'но', 'или', 'что', 'как', 'это', 'то', 'же', 'все', 'так'}
PUNCT_CHARS_SET = set('.,;:!?()[]{}"\'-')

def detect_suspicious(entity):
    """Детектирует подозрительные паттерны."""
    text = entity['text']
    label = entity['label']
    issues = []

    # Начинается/заканчивается пунктуацией
    if text and text[0] in PUNCT_CHARS_SET:
        issues.append(f"Starts with punct: '{text[0]}'")
    if text and text[-1] in PUNCT_CHARS_SET and label not in ['Email']:
        issues.append(f"Ends with punct: '{text[-1]}'")

    # Содержит только стоп-слова
    words = set(text.lower().split())
    if words and words.issubset(STOP_WORDS):
        issues.append("Only stop-words")

    # Содержит "..." или много пробелов
    if '...' in text:
        issues.append("Contains '...'")
    if '  ' in text:
        issues.append("Contains double spaces")

    # Для числовых сущностей - проверяем наличие букв где не должно быть
    numeric_labels = ['CVV/CVC', 'ПИН код', 'СНИЛС клиента', 'Сведения об ИНН', 'Номер банковского счета']
    if label in numeric_labels:
        cleaned = re.sub(r'[\s\-]', '', text)
        if re.search(r'[а-яА-ЯёЁa-zA-Z]', cleaned):
            issues.append("Letters in numeric field")

    # Подозрительно короткое для текстовых сущностей
    text_labels = ['ФИО', 'Место рождения', 'Полный адрес', 'Кодовые слова']
    if label in text_labels and len(text) < 3:
        issues.append("Too short for text field")

    return issues

# Проверяем все сущности (используем entities_h2)
suspicious = []
for e in entities_h2:
    issues = detect_suspicious(e)
    if issues:
        suspicious.append({**e, 'issues': issues})

print(f"Suspicious entities: {len(suspicious)} / {len(entities_h2)} ({100*len(suspicious)/len(entities_h2):.1f}%)")
print()

# Группируем по типу проблемы
by_issue = defaultdict(list)
for e in suspicious:
    for issue in e['issues']:
        by_issue[issue].append(e)

print("By issue type:")
for issue, items in sorted(by_issue.items(), key=lambda x: -len(x[1])):
    print(f"\n{issue}: {len(items)}")
    for item in items[:50]:
        print(f"  ID {item['id']} | {item['label']}: '{item['text'][:40]}'")
    if len(items) > 5:
        print(f"  ... and {len(items) - 5} more")

"""## Hypothesis 6: Length Distribution by Label

Анализ распределения длин по типам сущностей - выбросы могут быть ошибками
"""

# Статистика длин по типам (используем entities_h2)
import numpy as np

length_stats = defaultdict(list)
for e in entities_h2:
    length_stats[e['label']].append(e['length'])

print("Length statistics by label:")
print(f"{'Label':<60} {'Count':>6} {'Min':>5} {'Max':>5} {'Mean':>6} {'Std':>6}")
print("-" * 95)

for label in sorted(length_stats.keys()):
    lengths = length_stats[label]
    print(f"{label:<60} {len(lengths):>6} {min(lengths):>5} {max(lengths):>5} {np.mean(lengths):>6.1f} {np.std(lengths):>6.1f}")

# Находим выбросы по длине (> mean + 2*std или < mean - 2*std)
outliers = []

for label, lengths in length_stats.items():
    mean_len = np.mean(lengths)
    std_len = np.std(lengths)

    for e in entities_h2:
        if e['label'] == label:
            if e['length'] > mean_len + 2*std_len or e['length'] < mean_len - 2*std_len:
                outliers.append({**e, 'mean': mean_len, 'std': std_len})

print(f"Length outliers (outside mean +/- 2*std): {len(outliers)}")
print()

# Группируем по лейблам
outliers_by_label = defaultdict(list)
for e in outliers:
    outliers_by_label[e['label']].append(e)

for label, items in sorted(outliers_by_label.items(), key=lambda x: -len(x[1])):
    print(f"\n{label} (mean={items[0]['mean']:.1f}, std={items[0]['std']:.1f}): {len(items)} outliers")
    for item in items[:3]:
        print(f"  ID {item['id']} (len={item['length']}): '{item['text'][:50]}'")
    if len(items) > 3:
        print(f"  ... and {len(items) - 3} more")

"""## Summary: All Issues Found

Сводка всех найденных проблем
"""

# SUMMARY: Итоговая статистика после H1 и H2
# H1: Удаление коротких буквенных спанов ("с")
# H3: Date Expansion отключён - короткие даты соответствуют ground truth

print("=" * 60)
print("SUMMARY AFTER POST-PROCESSING")
print("=" * 60)

# Оригинал
orig_entities = parse_all_predictions(preds_df, texts_df)

# После расширения спанов до границ слов
exp_entities = parse_all_predictions(expanded_df, texts_df)

# После H1 (удаление коротких букв)
h1_entities = parse_all_predictions(h1_df, texts_df)

# После H2 (удаление пересекающихся)
h2_entities = parse_all_predictions(h2_df, texts_df)

print(f"Original entities:           {len(orig_entities)}")
print(f"After expand to word:        {len(exp_entities)} (-{len(orig_entities) - len(exp_entities)} punct removed)")
print(f"After H1 (short letters):    {len(h1_entities)} (-{len(exp_entities) - len(h1_entities)} removed)")
print(f"After H2 (overlapping):      {len(h2_entities)} (-{len(h1_entities) - len(h2_entities)} removed)")
print()
print(f"Total entities: {len(h2_entities)}")
print(f"Total removed: {len(orig_entities) - len(h2_entities)}")
print()
print("NOTE: H3 (Date Expansion) отключён - короткие даты ('19', '1', '25')")
print("      соответствуют ground truth разметке в train_dataset")
print()

# Финальный файл
final_output = "bert_final_postprocessed.csv"
h2_df.to_csv(final_output, index=False)
print(f"Final result saved to: {final_output}")